package com.michalklempa.playground.ui;

import com.michalklempa.playground.MessageService;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.button.ButtonVariant;
import com.vaadin.flow.component.card.Card;
import com.vaadin.flow.component.combobox.ComboBox;
import com.vaadin.flow.component.html.*;
import com.vaadin.flow.component.icon.VaadinIcon;
import com.vaadin.flow.component.notification.Notification;
import com.vaadin.flow.component.notification.NotificationVariant;
import com.vaadin.flow.component.orderedlayout.FlexComponent;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.popover.Popover;
import com.vaadin.flow.component.popover.PopoverPosition;
import com.vaadin.flow.component.popover.PopoverVariant;
import com.vaadin.flow.component.upload.Upload;
import com.vaadin.flow.server.streams.InMemoryUploadCallback;
import com.vaadin.flow.server.streams.UploadHandler;

class Message extends Card {

    Message(MessageService messageService) {
        setWidthFull();

        ComboBox<String> type = new ComboBox<>();

        Upload descriptor = new Upload(UploadHandler.inMemory(
                (InMemoryUploadCallback) (metadata, data) -> {
                    messageService.load(data);
                }));
        messageService.onLoadListeners.add(loadResult -> {
            descriptor.clearFileList();
            if (loadResult.success) {
                type.setItems(loadResult.names);
                type.setEnabled(true);
                return;
            }
            type.setEnabled(false);
            messageService.select(null);
            Notification notification = Notification.show(
                    "Invalid .desc file: " + loadResult.message, 5000, Notification.Position.MIDDLE);
            notification.addThemeVariants(NotificationVariant.ERROR);
        });

        descriptor.setAutoUpload(true);
        descriptor.setMaxFiles(1);
        descriptor.setAcceptedFileTypes(".desc", "application/octet-stream");
        descriptor.setDropAllowed(true);

        var help = new Button(VaadinIcon.QUESTION_CIRCLE.create());
        help.addThemeVariants(ButtonVariant.LUMO_TERTIARY, ButtonVariant.LUMO_SMALL);

        var popover = new Popover();
        popover.setTarget(help);
        popover.setPosition(PopoverPosition.BOTTOM_START);
        popover.addThemeVariants(PopoverVariant.LUMO_ARROW);
        var cmd = new Span("protoc --descriptor_set_out=out.desc --include_imports *.proto");
        cmd.getStyle().set("font-family", "monospace");
        popover.add(
                new Paragraph("A FileDescriptorSet binary generated by protoc"),
                cmd,
                new Anchor("https://protobuf.dev/programming-guides/proto3/", "docs ↗")
        );

        var uploadLabel = new HorizontalLayout(new Span("Descriptor File (.desc)"), help);
        uploadLabel.setAlignItems(FlexComponent.Alignment.CENTER);
        uploadLabel.setSpacing(false);

        var uploadSection = new HorizontalLayout(uploadLabel, descriptor);
        uploadSection.setPadding(false);
        uploadSection.setSpacing(false);

        var messageTypeLabel = new HorizontalLayout(new Span("Message Type"));
        messageTypeLabel.setAlignItems(FlexComponent.Alignment.CENTER);
        messageTypeLabel.setSpacing(false);

        type.addValueChangeListener(e -> {
            messageService.select(e.getValue());
        });

        type.setRequired(true);
        type.setEnabled(false);

        var typeSection = new HorizontalLayout(messageTypeLabel, type);
        typeSection.setFlexGrow(1, type);
        var row = new HorizontalLayout(uploadSection, typeSection);

        row.setAlignItems(FlexComponent.Alignment.CENTER);
        row.setWidthFull();
        row.setFlexGrow(1, typeSection);

        add(row);

        var schema = new Schema(messageService);
        add(schema);
    }
}
